sudo: required

env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1

services:
  - docker

script:
  - docker build -t zokeber/cpuminer-multi:latest .
  - docker create -it --name cpuminer-multi zokeber/cpuminer-multi:latest
  - docker start cpuminer-multi
  - docker stop cpuminer-multi
  - docker rm -f cpuminer-multi
